sourceDir = "~/setup"
[git]
    autoPush = true
[edit]
  command="vim"
[diff]
    command = "vim"
    args = ["-d", "{{ .Destination }}", "{{ .Target }}"]
[merge]
    command = "vim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
