[manager]
ratio          = [ 1, 2, 3 ]
show_hidden    = true
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 4600
max_height      = 4600
image_filter    = "triangle"
image_quality   = 80
sixel_fraction  = 15
ueberzug_scale  = 3
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = 'nvim "%*"',                              block = true, for = "windows" },
]

# [open]
# rules = [
# 	{ mime = "image/vnd.djvu", use = [ "zathura" ] },
# 	{ mime = "image/vnd.djvu+multipage", use = [ "zathura" ] },
# 	{ mime = "image/*", use = [ "imv" ] },
# 	{ mime = "video/*", use = [ "play", "reveal" ] },
# 	{ mime = "audio/*", use = [ "play", "reveal" ] },
# 	{ mime = "application/json", use = [ "edit", "reveal" ] },
# 	{ mime = "application/pdf", use = [ "zathura" ] },
# 	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },
#
# 	{ mime = "application/zip",             use = [ "extract", "reveal" ] },
# 	{ mime = "application/gzip",            use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-tar",           use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-bzip",          use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-bzip2",         use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-rar",           use = [ "extract", "reveal" ] },
# 	{ mime = "application/xz",              use = [ "extract", "reveal" ] },
#
# ]

# [plugin]
# prepend_previewers = [
# 	# Archive previewer
# 	{ mime = "application/*zip",            run = "ouch" },
# 	{ mime = "application/x-tar",           run = "ouch" },
# 	{ mime = "application/x-bzip2",         run = "ouch" },
# 	{ mime = "application/x-7z-compressed", run = "ouch" },
# 	{ mime = "application/x-rar",           run = "ouch" },
# 	{ mime = "application/x-xz",            run = "ouch" },
# ]


# This plugin does not provide a decompression feature because it already is supported by Yazi. To decompress with ouch, configure the opener in yazi.toml.
# [opener]
# extract = [
# 	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
# 	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
# ]
