[manager]
ratio          = [ 1, 2, 3 ]
show_hidden    = true
show_symlink   = true

[preview]
tab_size        = 4
max_width       = 1200
max_height      = 1200
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = 'nvim "%*"',                              block = true, for = "windows" },
]

# [open]
# rules = [
# 	{ mime = "image/vnd.djvu", use = [ "zathura" ] },
# 	{ mime = "image/vnd.djvu+multipage", use = [ "zathura" ] },
# 	{ mime = "image/*", use = [ "imv" ] },
# 	{ mime = "video/*", use = [ "play", "reveal" ] },
# 	{ mime = "audio/*", use = [ "play", "reveal" ] },
# 	{ mime = "application/json", use = [ "edit", "reveal" ] },
# 	{ mime = "application/pdf", use = [ "zathura" ] },
# 	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },
#
# 	{ mime = "application/zip",             use = [ "extract", "reveal" ] },
# 	{ mime = "application/gzip",            use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-tar",           use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-bzip",          use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-bzip2",         use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
# 	{ mime = "application/x-rar",           use = [ "extract", "reveal" ] },
# 	{ mime = "application/xz",              use = [ "extract", "reveal" ] },
#
# ]




