#!/bin/zsh

alias ll='ls -alF --color'
alias vim='nvim'
# alias vimd="nvim ~/.dotfiles"
alias hm="home-manager"
alias hmd="cd ~/.config/home-manager"
alias hms="home-manager switch" # --flake ~/.config/home-manager#adrab"
alias hme="home-manager edit"
alias hmp="home-manager packages"
alias hmu="nix flake update ~/.config/home-manager && hms"
alias chezmoi='chezmoi -c ~/setup/chezmoi/chezmoi.toml'
alias che="chezmoi edit"
alias cheh="chezmoi edit ~/.config/home-manager/home.nix"
alias chea="chezmoi edit ~/.config/zsh/aliases"
alias cha='chezmoi apply'
alias scalanew3='sbt new scala/scala3.g8'
alias scalanew3cross='sbt new scala/scala3-cross.g8'

