-- require 'treesitter-context'.setup {
--   max_lines = 2,
--   trim_scope = 'inner',
--   -- Separator between context and content. Should be a single character string, like '-'.
--   -- When separator is set, the context will only show up when there are at least 2 lines above cursorline.
--   separator = nil,
-- }
